services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: .
    container_name: finance-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redislabs/rejson:latest
    container_name: redis-json
    ports:
      - "6379:6379"

volumes:
  ollama_data: